# Generated by Django 3.2.8 on 2022-03-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
