# Generated by Django 3.2.8 on 2022-03-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
